# Generated by Django 2.2.6 on 2020-01-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(blank=True, max_length=64, null=True)),
                ('app_version', models.CharField(blank=True, max_length=32, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('was_online', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'authorized_device',
            },
        ),
    ]
