# Generated by Django 2.2.6 on 2020-01-29 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import encrypted_fields.fields
import ik.fields.unsignedauto
import ik.utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('region', models.SmallIntegerField()),
                ('language', models.CharField(max_length=3)),
                ('currency', models.CharField(max_length=3)),
                ('phone_code', models.CharField(max_length=5)),
                ('timezone', models.IntegerField()),
                ('de', models.CharField(max_length=60)),
                ('en', models.CharField(max_length=60)),
                ('ru', models.CharField(max_length=60)),
                ('pl', models.CharField(max_length=60)),
                ('es', models.CharField(max_length=60)),
                ('it', models.CharField(max_length=60)),
                ('fr', models.CharField(max_length=60)),
                ('th', models.CharField(max_length=60)),
                ('ja', models.CharField(db_column='jp', default='', max_length=255)),
                ('tr', models.CharField(max_length=60)),
                ('pt', models.CharField(max_length=60)),
                ('zh_CN', models.CharField(db_column='zh', default='', max_length=255)),
                ('ko', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'countries',
                'ordering': ('en',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', ik.fields.unsignedauto.UnsignedAutoField(primary_key=True, serialize=False)),
                ('displayname', models.CharField(max_length=100, verbose_name='Display name')),
                ('userid', models.CharField(db_index=True, default='', max_length=16, verbose_name='UserID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last name')),
                ('password', models.CharField(default='', max_length=128, verbose_name='Password')),
                ('_email_data', encrypted_fields.fields.EncryptedCharField(editable=False, max_length=128)),
                ('email', encrypted_fields.fields.SearchField(db_index=True, encrypted_field_name='_email_data', hash_key='3c8d901b1fd99e7c5238df8205e57c0c', max_length=66, null=True, unique=True, verbose_name='Email')),
                ('_phone_data', encrypted_fields.fields.EncryptedCharField(blank=True, editable=False, max_length=22, null=True)),
                ('phone', encrypted_fields.fields.SearchField(db_index=True, encrypted_field_name='_phone_data', hash_key='5998b869dbeffe7daf52794ded2f9a91', max_length=66, null=True, verbose_name='Phone')),
                ('profile_image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', max_length=255, upload_to=ik.utils.storage.UUIDPath('profile'))),
                ('riscos', models.CharField(default='', max_length=64, verbose_name='RiscOS platform')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('push_channel', models.CharField(max_length=34, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('photo_image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', max_length=255, upload_to=ik.utils.storage.UUIDPath('chat'))),
                ('is_group', models.BooleanField(default=False)),
                ('is_common_history', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='GlobalVars',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=16000)),
                ('valid_to', models.DateTimeField()),
            ],
            options={
                'db_table': 'global_vars',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[(1, 'Text'), (2, 'File'), (3, 'Photo'), (4, 'Sticker'), (5, 'Audio'), (6, 'Video'), (7, 'Contact'), (8, 'Loacation'), (9, 'Join'), (9, 'Leave'), (9, 'Call'), (12, 'Poll')], verbose_name='Message type')),
                ('text', encrypted_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('sendtime', models.DateTimeField(auto_now_add=True, verbose_name='Send time')),
                ('changedtime', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_messages', to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ik.Chat')),
                ('reply_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='ik.Message')),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
        migrations.CreateModel(
            name='OpenedChat',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='opened_chat', serialize=False, to='api.AuthorizedDevice')),
                ('chat_id', models.CharField(db_index=True, max_length=65)),
            ],
            options={
                'db_table': 'chat_opened',
            },
        ),
        migrations.CreateModel(
            name='AttachmentFile',
            fields=[
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attachment_file', serialize=False, to='ik.Message')),
                ('file', models.FileField(default=None, max_length=255, upload_to=ik.utils.storage.UUIDPath('attachment'))),
                ('file_type', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'attachments_file',
            },
        ),
        migrations.CreateModel(
            name='AttachmentPhoto',
            fields=[
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attachment_photo', serialize=False, to='ik.Message')),
                ('file', models.ImageField(default=None, max_length=255, upload_to=ik.utils.storage.UUIDPath('attachment'))),
            ],
            options={
                'db_table': 'attachments_photo',
            },
        ),
        migrations.CreateModel(
            name='MemberLoginCode',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code', models.CharField(default='', max_length=8)),
                ('created_at', models.DateTimeField(null=True)),
                ('used_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'member_login_code',
            },
        ),
        migrations.CreateModel(
            name='MemberOnline',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='online', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('online', models.BooleanField(default=False)),
                ('was_online', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Member online',
                'verbose_name_plural': 'Members online',
                'db_table': 'members_online',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ik.Message'),
        ),
        migrations.CreateModel(
            name='MemberSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('data', models.CharField(max_length=16000)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member_settings',
                'unique_together': {('member', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DeletedMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ik.Message')),
            ],
            options={
                'db_table': 'messages_deleted',
                'unique_together': {('member', 'message')},
            },
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hide_msg_upto_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=3)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatmembers', to='ik.Chat')),
                ('last_seen_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ik.Message')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_members',
                'unique_together': {('chat', 'member')},
            },
        ),
    ]
