# Generated by Django 2.2.9 on 2020-02-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0008_auto_20200210_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
