# Generated by Django 2.2.9 on 2020-05-31 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0009_attachmentfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ik.Message'),
        ),
        migrations.AlterField(
            model_name='attachmentfile',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Text'), (2, 'File'), (3, 'Photo'), (4, 'Sticker'), (5, 'Audio'), (6, 'Video'), (7, 'Contact'), (8, 'Loacation'), (9, 'Join'), (10, 'Leave'), (11, 'Call'), (12, 'Poll')], verbose_name='Message type'),
        ),
    ]
