# Generated by Django 2.2.9 on 2020-12-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0011_auto_20201204_1128'),
        ('ik', '0011_chatmessageentities'),
    ]

    operations = [
    ]
