# Generated by Django 2.2.9 on 2020-12-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0012_merge_20201204_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberonline',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
