# Generated by Django 2.2.9 on 2021-01-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0013_memberonline_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='last_message',
        ),
    ]
