# Generated by Django 2.2.9 on 2021-06-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik', '0014_remove_chat_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
