# offline detection
MAX_IDLE_TIME = 180

MESSENGER_CHATCUBE = 'C'
MESSENGER_TG = 'T'
MESSENGER_FB = 'F'
MESSENGERS = (
    (MESSENGER_CHATCUBE, 'ChatCube'),
    (MESSENGER_TG, 'Telegram'),
    (MESSENGER_FB, 'Facebook'),
)

CHAT_TYPE_PRIVATE = 1
CHAT_TYPE_SECRET = 2
CHAT_TYPE_GROUP = 50
CHAT_TYPE_CHANNEL = 100

CHATMEMBER_STATUS_CREATOR = 1
CHATMEMBER_STATUS_ADMIN = 2
CHATMEMBER_STATUS_NORMAL = 3
CHATMEMBER_STATUS_READONLY = 4
CHATMEMBER_STATUS_BANNED = 5
CHATMEMBER_STATUS_DELETED = 6
CHATMEMBER_STATUSES = (
    (CHATMEMBER_STATUS_CREATOR, 'Creator'),
    (CHATMEMBER_STATUS_ADMIN, 'Admin'),
    (CHATMEMBER_STATUS_NORMAL, 'Normal'),
    (CHATMEMBER_STATUS_READONLY, 'Read-only'),
    (CHATMEMBER_STATUS_BANNED, 'Banned'),
    (CHATMEMBER_STATUS_DELETED, 'Banned')
)

MESSAGE_TYPE_TEXT = 1
MESSAGE_TYPE_FILE = 2
MESSAGE_TYPE_PHOTO = 3
MESSAGE_TYPE_STICKER = 4
MESSAGE_TYPE_AUDIO = 5
MESSAGE_TYPE_VIDEO = 6
MESSAGE_TYPE_CONTACT = 7
MESSAGE_TYPE_LOCATION = 8
MESSAGE_TYPE_JOIN = 9
MESSAGE_TYPE_LEAVE = 10
MESSAGE_TYPE_CALL = 11
MESSAGE_TYPE_POLL = 12
MESSAGE_TYPE_CUSTOM_TYPE = 100
MESSAGE_TYPES = (
    (MESSAGE_TYPE_TEXT, 'Text'),
    (MESSAGE_TYPE_FILE, 'File'),
    (MESSAGE_TYPE_PHOTO, 'Photo'),
    (MESSAGE_TYPE_STICKER, 'Sticker'),
    (MESSAGE_TYPE_AUDIO, 'Audio'),
    (MESSAGE_TYPE_VIDEO, 'Video'),
    (MESSAGE_TYPE_CONTACT, 'Contact'),
    (MESSAGE_TYPE_LOCATION, 'Loacation'),
    (MESSAGE_TYPE_JOIN, 'Join'),
    (MESSAGE_TYPE_LEAVE, 'Leave'),
    (MESSAGE_TYPE_CALL, 'Call'),
    (MESSAGE_TYPE_POLL, 'Poll'),
)

MESSAGE_SENDING_STATE_SUCCESS = 0
MESSAGE_SENDING_STATE_PENDING = 1
MESSAGE_SENDING_STATE_FAILED = 2

MESSAGE_FLAG_OUTGOING = 1
MESSAGE_FLAG_SYSTEM = 2
MESSAGE_FLAG_DELETED = 4
MESSAGE_FLAG_CAN_BE_EDITED = 8

TEXT_ENTITY_BOLD = 2
TEXT_ENTITY_ITALIC = 3
TEXT_ENTITY_UNDERLINE = 4
TEXT_ENTITY_PHONE = 8
TEXT_ENTITY_EMAIL = 9
TEXT_ENTITY_URL = 10
TEXT_ENTITY_TEXT_URL = 11

CHAT_ACTION_CANCEL = 0
CHAT_ACTION_TYPING = 1

